### ISSUE TITLE
mod-h and mod-l are reversed

### ISSUE THREAD

**Issue by onyxperidot** [emillon/dotxmonad#1]
The default xmonad semantics of mod-h and mod-l were:

mod-h  Shrink the master area
mod-l  Expand the master area

After loading your xmonad.hs, the behavior of mod-h and mod-l is reversed.

**Comment by emillon** [comment]
Hi,

Thanks for the feedback!

These bindings are not actually redefined in this configuration. But the default layout is flipped, so the master area is actually on the right part and will shrink with `M-h`. I agree that it's a bit unintuitive so I may change it for consistency.

**Comment by onyxperidot** [comment]
Hi,

Thanks for your response.  I initially tried to figuring it out for myself by reading your code, but I could not find the bindings.  That's why I raised the issue.  I read a book on Haskell in 1996 and have never done anything useful with it ever since. I enjoy reading your code and at the same time I get to learn a tiny bit of French too.

**Comment by onyxperidot** [comment]
By the way, I now understand what 'reflectHoriz tiled ||| Full' means in Layout.hs.  Thanks again.

**Comment by emillon** [comment]
Don't hesitate if you have other suggestions !
